name: byshop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  google_fonts: ^5.1.0
  badges: ^3.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Matemasie
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
