name: byshop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  badges: ^3.1.2
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  pay: ^2.0.0
  flutter_rating_bar: ^4.0.1
  file_picker: ^8.1.2
  dotted_border: ^2.1.0
  cloudinary_public: ^0.23.1
  intl: ^0.19.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/applepay.json
    - assets/gpay.json

  fonts:
    - family: Matemasie
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
